# Generated by Django 5.2.1 on 2025-05-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoApp', '0002_customuser_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='foto',
        ),
        migrations.AddField(
            model_name='menu',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='assets/'),
        ),
    ]
